openapi: 3.0.0
info:
  title:
  version:
tags:
paths:
  /produtos:
    post:
      summary: Cria um novo produto 
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      summary: Lista todos os produtos
      tags:
        - produtos
      responses:
        200:
          contents:
            application/json:
              schema:
                $ref: '#components/schemas/ArrayOfProdutos'
  /produtos/{id}:
    get:
      summary: Busca um produto pelo ID
      tags:
        - produtos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'            
components: 
  schemas:
  ArrayOfProdutos:
    type: array
    items:
      $ref: '#components/schemas/Produto'
    Produto:
      type: object
      properties:
        nome:
          type: string
        grupo:
          type: string
        preco:
          type: number
        quantidade:
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string