openapi: 3.0.0
info:
  title: API BlackBox
  version: 0.0.1
tags:
  - name: compras
paths:
  /compras: 
    post: 
      tags:
        - compras
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compra'
      responses:
        201:
          description: Cadastro de compra com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compra'
                  
        422:
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        500:
          description: Servidor não contactado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get: 
      tags:
        - compras
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compra'
      responses:
        200:
          description: Consultar todas as compras
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compra'
  /compras/{id}:
    get: 
      tags:
        - compras
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          description: Consultar uma compra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compra'
        400:
          description: Id Inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Compra não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - compras
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compra'
      responses:
        200:
          description: Compra atualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compra'
        400:
          description: Id Inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Compra não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'        
        422:
          description: Dados inválidos
          content:
            appication/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - compras
      parameters:
        - in: path
          type: string
          name: id
      responses:
        204:
          description: Compra Excluída
        400:
          description: Id Inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Compra não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

components: 
  schemas:
    ArrayOfCompras:
      type: array
      items:
        $ref: '#/components/schemas/Compra'
    Compra:
      type: object
      properties:
        produto:
          type: string
        preco:
          type: number
        quantidade: 
          type: number
        data:
          type: string
          format: date
        vendedor: 
          type: string
        nf: 
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string