openapi: 3.0.0
info:
  title: API CRUD de Fornecedores
  description: API para realizar operações CRUD em fornecedores.
  version: 1.0.0
tags:
  - fornecedor
paths:
  /fornecedor:
    post:
      tags:
        - fornecedor
      summary: Cadastra um fornecedor.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FornecedorInput'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FornecedorInput'
        422:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      tags:
        - fornecedor
      summary: Retorna uma lista de fornecedores.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FornecedorInput'
        400:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
  /fornecedor/{id}:
    get:
      summary: Busca um fornecedor pelo ID.
      tags:
        - fornecedor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - fornecedor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FornecedorInput'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - fornecedor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          content:
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
    Fornecedor:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        empresa:
          type: string
        cnpj:
          type: string
        email:
          type: string
        telefone:
          type: string
      required:
        - nome
        - empresa
        - cnpj
        - email
        - telefone

    FornecedorInput:
      type: object
      properties:
        nome:
          type: string
        empresa:
          type: string
        cnpj:
          type: string
        email:
          type: string
        telefone:
          type: string
      required:
        - nome
        - empresa
        - cnpj
        - email
        - telefone
    Mensagem:
      type: object
      properties:
        msg:
          type: string
